[options]
addons_path=/mnt/extra-addons
admin_passwd=admin
db_host=db
db_port=5432
db_user=odoo
db_password=odoo
db_name=miu_rnd_lab
db_maxconn=64
db_template=template0
demo={}
without_demo=all
email_from=noreply@miu-rnd.lab
logfile=/var/lib/odoo/logs/odoo.log
log_level=info
logrotate=True
max_cron_threads=2
server_wide_modules=base,web
workers=2
limit_memory_hard=536870912
limit_memory_soft=402653184
limit_request=8192
limit_time_cpu=60
limit_time_real=120
